// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkpxzvpizyetnrzxfrjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcHh6dnBpenlldG5yenhmcmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjE2MTksImV4cCI6MjA2ODkzNzYxOX0.xI2UYWmnCveuPLdl83_i3mO9suS5zXPAZWjotC2WlA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});